apiVersion: v1
kind: Pod
metadata:
  name: crashloop-pod
  namespace: monitoring
spec:
  restartPolicy: Always
  containers:
    - name: crashloop
      image: busybox
      command: ["/bin/sh", "-c", "exit 1"]
