apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting
  labels:
    app: accounting
spec:
  replicas: { .Values.replicaCount }
  selector:
    matchLabels:
      app: accounting
  template:
    metadata:
      labels:
        app: accounting
    spec:
      containers:
        - name: accounting
          image: "{{ .Values.images.accounting.repository }}:{{ .Values.images.accounting.tag }}"
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
