apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad
  labels:
    app: ad
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ad
  template:
    metadata:
      labels:
        app: ad
    spec:
      containers:
        - name: ad
          {{ $img := index .Values.images "ad" }}
          image: "{{ $img.repository }}:{{ $img.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
