apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  labels:
    app: currency
spec:
  replicas: { .Values.replicaCount }
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      containers:
        - name: currency
          image: "{{ .Values.images.currency.repository }}:{{ .Values.images.currency.tag }}"
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
