apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: email
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: email
          {{ $img := index .Values.images "email" }}
          image: "{{ $img.repository }}:{{ $img.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            {{ toYaml .Values.commonEnv | nindent 12 }}
          ports:
            - containerPort: 8080
