apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagd-ui
  labels:
    app: flagd-ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flagd-ui
  template:
    metadata:
      labels:
        app: flagd-ui
    spec:
      containers:
        - name: flagd-ui
          {{ $img := index .Values.images "flagd-ui" }}
          image: "{{ $img.repository }}:{{ $img.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
