apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
  labels:
    app: fraud-detection
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: fraud-detection
          {{ $img := index .Values.images "fraud-detection" }}
          image: "{{ $img.repository }}:{{ $img.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
