apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
  labels:
    app: fraud-detection
spec:
  type: ClusterIP
  selector:
    app: fraud-detection
  ports:
    - port: 8080
      targetPort: 8080
