apiVersion: v1
kind: Service
metadata:
  name: frontend-proxy
  labels:
    app: frontend-proxy
spec:
  type: ClusterIP
  selector:
    app: frontend-proxy
  ports:
    - port: 8080
      targetPort: 8080
