apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-proxy
  labels:
    app: frontend-proxy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend-proxy
  template:
    metadata:
      labels:
        app: frontend-proxy
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: frontend-proxy
          {{ $img := index .Values.images "frontend-proxy" }}
          image: "{{ $img.repository }}:{{ $img.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
