apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-provider
  labels:
    app: image-provider
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: image-provider
  template:
    metadata:
      labels:
        app: image-provider
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: image-provider
          {{ $img := index .Values.images "image-provider" }}
          image: "{{ $img.repository }}:{{ $img.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            {{ toYaml .Values.commonEnv | nindent 12 }}
          ports:
            - containerPort: 8080
