apiVersion: v1
kind: Service
metadata:
  name: image-provider
  labels:
    app: image-provider
spec:
  type: ClusterIP
  selector:
    app: image-provider
  ports:
    - port: 8080
      targetPort: 8080
