apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-provider
  labels:
    app: image-provider
spec:
  replicas: { .Values.replicaCount }
  selector:
    matchLabels:
      app: image-provider
  template:
    metadata:
      labels:
        app: image-provider
    spec:
      containers:
        - name: image-provider
          image: "{{ .Values.images.image-provider.repository }}:{{ .Values.images.image-provider.tag }}"
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
