apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: { .Values.replicaCount }
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: "{{ .Values.images.kafka.repository }}:{{ .Values.images.kafka.tag }}"
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
