apiVersion: v1
kind: Service
metadata:
  name: load-generator
  labels:
    app: load-generator
spec:
  type: ClusterIP
  selector:
    app: load-generator
  ports:
    - port: 8080
      targetPort: 8080
