apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: { .Values.replicaCount }
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: "{{ .Values.images.payment.repository }}:{{ .Values.images.payment.tag }}"
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
