spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
        - name: product-catalog
          {{- $img := index .Values.images "product-catalog" }}
          image: "{{ $img.repository }}:{{ $img.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
