apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
  labels:
    app: quote
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: quote
  template:
    metadata:
      labels:
        app: quote
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: quote
          {{ $img := index .Values.images "quote" }}
          image: "{{ $img.repository }}:{{ $img.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            {{ toYaml .Values.commonEnv | nindent 12 }}
          ports:
            - containerPort: 8080
