apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  labels:
    app: recommendation
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: recommendation
          {{ $img := index .Values.images "recommendation" }}
          image: "{{ $img.repository }}:{{ $img.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            {{ toYaml .Values.commonEnv | nindent 12 }}
          ports:
            - containerPort: 8080
