apiVersion: v1
kind: Service
metadata:
  name: recommendation
  labels:
    app: recommendation
spec:
  type: ClusterIP
  selector:
    app: recommendation
  ports:
    - port: 8080
      targetPort: 8080
