name: CI/CD for OpenTelemetry Demo (frontend only)

on:
  push:
    branches:
      - main

env:
  EKS_CLUSTER: otel-demo-cluster
  REGION: us-east-1
  HELM_RELEASE: otel-demo
  NAMESPACE: otel-demo
  REPO: ghcr.io/${{ github.repository }}

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push frontend image
      run: |
        docker build -t $REPO/frontend ./src/frontend
        docker push $REPO/frontend

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name $EKS_CLUSTER --region $REGION

    - name: Deploy frontend via Helm
      run: |
        helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
        helm repo update
        helm upgrade --install $HELM_RELEASE open-telemetry/opentelemetry-demo \
          --namespace $NAMESPACE --create-namespace \
          --set frontend.image=$REPO/frontend

    - name: Confirm frontend rollout
      run: kubectl rollout status deployment/frontend -n $NAMESPACE

  rollback-if-fails:
    needs: deploy-frontend
    if: failure()
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Rollback frontend
      run: |
        aws eks update-kubeconfig --name $EKS_CLUSTER --region $REGION
        helm rollback $HELM_RELEASE 1 -n $NAMESPACE
