name: Manual Helm & Smoke Tests for otel-demo-helm

on:
  workflow_dispatch:

env:
  EKS_CLUSTER: otel-demo-cluster
  REGION: us-east-1
  NAMESPACE: otel-demo-helm

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo (optional)
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name $EKS_CLUSTER --region $REGION

    - name: Test access to cluster
      run: kubectl get nodes

    - name: Run Helm tests for otel-demo-helm
      run: |
        helm test otel-ghcr -n $NAMESPACE || echo "Helm tests failed"

    - name: Port-forward and smoke test frontend-proxy in otel-demo-helm
      run: |
        kubectl port-forward -n $NAMESPACE svc/frontend-proxy 8080:8080 &
        sleep 10
        curl -f http://localhost:8080 || (echo "Smoke test failed" && exit 1)
